// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrgRsVVC1xAYkqemLBChdhZhw8v_F2VtA',
    appId: '1:193795419144:web:165da68bebfe3d0ee0f5bd',
    messagingSenderId: '193795419144',
    projectId: 'letschat-1f7ba',
    authDomain: 'letschat-1f7ba.firebaseapp.com',
    storageBucket: 'letschat-1f7ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrfJUvOxs8RbLpqOLDLNujS3Qj230wCsc',
    appId: '1:193795419144:android:7fb14fe93615ca33e0f5bd',
    messagingSenderId: '193795419144',
    projectId: 'letschat-1f7ba',
    storageBucket: 'letschat-1f7ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdTBjH4XzMyQ07cCGZ6h_HUYEvCCh8eyc',
    appId: '1:193795419144:ios:cce330b16ea21269e0f5bd',
    messagingSenderId: '193795419144',
    projectId: 'letschat-1f7ba',
    storageBucket: 'letschat-1f7ba.appspot.com',
    iosClientId: '193795419144-blskavlhql848k6ueo1pk0tqjj1nbmjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
